variable "env" {}
variable "vpc_cidr" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "azs" {}
variable "account_no" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_route_table_id" {}
variable "workstation_node_cidr" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_capacity" {}
variable "instance_class" {}
variable "prometheus_cidr" {}
variable "kms_key_id" {}
variable "project_name" {}
variable "instance_types" {}
variable "node_count" {}